version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tuoguanyi
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./.data/postgre:/var/lib/postgresql/data/
