version: '3.9'
services:
  xsn-boot:
    image: xsnnet:1.0
    container_name: xsn-boot
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=prod
    volumes:
      - /work/www/xsn-boot/xsn-server.jar:/app/app.jar